package entity;
// Generated Jun 14, 2017 10:42:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Anio generated by hbm2java
 */
public class Anio  implements java.io.Serializable {


     private int idAnio;
     private Integer anio;
     private String nombreAnio;
     private Set meses = new HashSet(0);

    public Anio() {
    }

	
    public Anio(int idAnio) {
        this.idAnio = idAnio;
    }
    public Anio(int idAnio, Integer anio, String nombreAnio, Set meses) {
       this.idAnio = idAnio;
       this.anio = anio;
       this.nombreAnio = nombreAnio;
       this.meses = meses;
    }
   
    public int getIdAnio() {
        return this.idAnio;
    }
    
    public void setIdAnio(int idAnio) {
        this.idAnio = idAnio;
    }
    public Integer getAnio() {
        return this.anio;
    }
    
    public void setAnio(Integer anio) {
        this.anio = anio;
    }
    public String getNombreAnio() {
        return this.nombreAnio;
    }
    
    public void setNombreAnio(String nombreAnio) {
        this.nombreAnio = nombreAnio;
    }
    public Set getMeses() {
        return this.meses;
    }
    
    public void setMeses(Set meses) {
        this.meses = meses;
    }




}


