package entity;
// Generated Jun 14, 2017 10:42:03 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Bono generated by hbm2java
 */
public class Bono  implements java.io.Serializable {


     private int nroDocumento;
     private CentroDeSalud centroDeSalud;
     private Dia dia;
     private Hora hora;
     private Oficina oficina;
     private Paciente paciente;
     private Sociedad sociedad;
     private int totalValor;
     private Integer bonificacionSeguro;
     private int totalBonificacion;
     private int totalConvenio;
     private int totalCopago;
     private String estado;
     private Date fecha;
     private Serializable idDetalleBono;
     private Set detalleBonos = new HashSet(0);

    public Bono() {
    }

	
    public Bono(int nroDocumento, Oficina oficina, Paciente paciente, Sociedad sociedad, int totalValor, int totalBonificacion, int totalConvenio, int totalCopago, String estado) {
        this.nroDocumento = nroDocumento;
        this.oficina = oficina;
        this.paciente = paciente;
        this.sociedad = sociedad;
        this.totalValor = totalValor;
        this.totalBonificacion = totalBonificacion;
        this.totalConvenio = totalConvenio;
        this.totalCopago = totalCopago;
        this.estado = estado;
    }
    public Bono(int nroDocumento, CentroDeSalud centroDeSalud, Dia dia, Hora hora, Oficina oficina, Paciente paciente, Sociedad sociedad, int totalValor, Integer bonificacionSeguro, int totalBonificacion, int totalConvenio, int totalCopago, String estado, Date fecha, Serializable idDetalleBono, Set detalleBonos) {
       this.nroDocumento = nroDocumento;
       this.centroDeSalud = centroDeSalud;
       this.dia = dia;
       this.hora = hora;
       this.oficina = oficina;
       this.paciente = paciente;
       this.sociedad = sociedad;
       this.totalValor = totalValor;
       this.bonificacionSeguro = bonificacionSeguro;
       this.totalBonificacion = totalBonificacion;
       this.totalConvenio = totalConvenio;
       this.totalCopago = totalCopago;
       this.estado = estado;
       this.fecha = fecha;
       this.idDetalleBono = idDetalleBono;
       this.detalleBonos = detalleBonos;
    }
   
    public int getNroDocumento() {
        return this.nroDocumento;
    }
    
    public void setNroDocumento(int nroDocumento) {
        this.nroDocumento = nroDocumento;
    }
    public CentroDeSalud getCentroDeSalud() {
        return this.centroDeSalud;
    }
    
    public void setCentroDeSalud(CentroDeSalud centroDeSalud) {
        this.centroDeSalud = centroDeSalud;
    }
    public Dia getDia() {
        return this.dia;
    }
    
    public void setDia(Dia dia) {
        this.dia = dia;
    }
    public Hora getHora() {
        return this.hora;
    }
    
    public void setHora(Hora hora) {
        this.hora = hora;
    }
    public Oficina getOficina() {
        return this.oficina;
    }
    
    public void setOficina(Oficina oficina) {
        this.oficina = oficina;
    }
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }
    public Sociedad getSociedad() {
        return this.sociedad;
    }
    
    public void setSociedad(Sociedad sociedad) {
        this.sociedad = sociedad;
    }
    public int getTotalValor() {
        return this.totalValor;
    }
    
    public void setTotalValor(int totalValor) {
        this.totalValor = totalValor;
    }
    public Integer getBonificacionSeguro() {
        return this.bonificacionSeguro;
    }
    
    public void setBonificacionSeguro(Integer bonificacionSeguro) {
        this.bonificacionSeguro = bonificacionSeguro;
    }
    public int getTotalBonificacion() {
        return this.totalBonificacion;
    }
    
    public void setTotalBonificacion(int totalBonificacion) {
        this.totalBonificacion = totalBonificacion;
    }
    public int getTotalConvenio() {
        return this.totalConvenio;
    }
    
    public void setTotalConvenio(int totalConvenio) {
        this.totalConvenio = totalConvenio;
    }
    public int getTotalCopago() {
        return this.totalCopago;
    }
    
    public void setTotalCopago(int totalCopago) {
        this.totalCopago = totalCopago;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Serializable getIdDetalleBono() {
        return this.idDetalleBono;
    }
    
    public void setIdDetalleBono(Serializable idDetalleBono) {
        this.idDetalleBono = idDetalleBono;
    }
    public Set getDetalleBonos() {
        return this.detalleBonos;
    }
    
    public void setDetalleBonos(Set detalleBonos) {
        this.detalleBonos = detalleBonos;
    }




}


