package entity;
// Generated Jun 14, 2017 10:42:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CentroDeSalud generated by hbm2java
 */
public class CentroDeSalud  implements java.io.Serializable {


     private int idCentroDeSalud;
     private String nombreCentro;
     private String direccionCentro;
     private Set bonos = new HashSet(0);

    public CentroDeSalud() {
    }

	
    public CentroDeSalud(int idCentroDeSalud) {
        this.idCentroDeSalud = idCentroDeSalud;
    }
    public CentroDeSalud(int idCentroDeSalud, String nombreCentro, String direccionCentro, Set bonos) {
       this.idCentroDeSalud = idCentroDeSalud;
       this.nombreCentro = nombreCentro;
       this.direccionCentro = direccionCentro;
       this.bonos = bonos;
    }
   
    public int getIdCentroDeSalud() {
        return this.idCentroDeSalud;
    }
    
    public void setIdCentroDeSalud(int idCentroDeSalud) {
        this.idCentroDeSalud = idCentroDeSalud;
    }
    public String getNombreCentro() {
        return this.nombreCentro;
    }
    
    public void setNombreCentro(String nombreCentro) {
        this.nombreCentro = nombreCentro;
    }
    public String getDireccionCentro() {
        return this.direccionCentro;
    }
    
    public void setDireccionCentro(String direccionCentro) {
        this.direccionCentro = direccionCentro;
    }
    public Set getBonos() {
        return this.bonos;
    }
    
    public void setBonos(Set bonos) {
        this.bonos = bonos;
    }




}


