package entity;
// Generated Jun 14, 2017 10:42:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cotizante generated by hbm2java
 */
public class Cotizante  implements java.io.Serializable {


     private int idCotizante;
     private Prevision prevision;
     private Seguro seguro;
     private String nombreCotizante;
     private String apellidoCotizante;
     private String rutCotizante;
     private Set pacientes = new HashSet(0);

    public Cotizante() {
    }

	
    public Cotizante(int idCotizante, String nombreCotizante, String apellidoCotizante, String rutCotizante) {
        this.idCotizante = idCotizante;
        this.nombreCotizante = nombreCotizante;
        this.apellidoCotizante = apellidoCotizante;
        this.rutCotizante = rutCotizante;
    }
    public Cotizante(int idCotizante, Prevision prevision, Seguro seguro, String nombreCotizante, String apellidoCotizante, String rutCotizante, Set pacientes) {
       this.idCotizante = idCotizante;
       this.prevision = prevision;
       this.seguro = seguro;
       this.nombreCotizante = nombreCotizante;
       this.apellidoCotizante = apellidoCotizante;
       this.rutCotizante = rutCotizante;
       this.pacientes = pacientes;
    }
   
    public int getIdCotizante() {
        return this.idCotizante;
    }
    
    public void setIdCotizante(int idCotizante) {
        this.idCotizante = idCotizante;
    }
    public Prevision getPrevision() {
        return this.prevision;
    }
    
    public void setPrevision(Prevision prevision) {
        this.prevision = prevision;
    }
    public Seguro getSeguro() {
        return this.seguro;
    }
    
    public void setSeguro(Seguro seguro) {
        this.seguro = seguro;
    }
    public String getNombreCotizante() {
        return this.nombreCotizante;
    }
    
    public void setNombreCotizante(String nombreCotizante) {
        this.nombreCotizante = nombreCotizante;
    }
    public String getApellidoCotizante() {
        return this.apellidoCotizante;
    }
    
    public void setApellidoCotizante(String apellidoCotizante) {
        this.apellidoCotizante = apellidoCotizante;
    }
    public String getRutCotizante() {
        return this.rutCotizante;
    }
    
    public void setRutCotizante(String rutCotizante) {
        this.rutCotizante = rutCotizante;
    }
    public Set getPacientes() {
        return this.pacientes;
    }
    
    public void setPacientes(Set pacientes) {
        this.pacientes = pacientes;
    }




}


