package entity;
// Generated Jun 22, 2017 9:58:54 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Juego generated by hbm2java
 */
public class Juego  implements java.io.Serializable {


     private int idJuego;
     private String combinacion;
     private int ganadorAciertos;
     private Set usuarioJuegos = new HashSet(0);
     private Set juegoSorteos = new HashSet(0);

    public Juego() {
    }

	
    public Juego(int idJuego, String combinacion, int ganadorAciertos) {
        this.idJuego = idJuego;
        this.combinacion = combinacion;
        this.ganadorAciertos = ganadorAciertos;
    }
    public Juego(int idJuego, String combinacion, int ganadorAciertos, Set usuarioJuegos, Set juegoSorteos) {
       this.idJuego = idJuego;
       this.combinacion = combinacion;
       this.ganadorAciertos = ganadorAciertos;
       this.usuarioJuegos = usuarioJuegos;
       this.juegoSorteos = juegoSorteos;
    }
   
    public int getIdJuego() {
        return this.idJuego;
    }
    
    public void setIdJuego(int idJuego) {
        this.idJuego = idJuego;
    }
    public String getCombinacion() {
        return this.combinacion;
    }
    
    public void setCombinacion(String combinacion) {
        this.combinacion = combinacion;
    }
    public int getGanadorAciertos() {
        return this.ganadorAciertos;
    }
    
    public void setGanadorAciertos(int ganadorAciertos) {
        this.ganadorAciertos = ganadorAciertos;
    }
    public Set getUsuarioJuegos() {
        return this.usuarioJuegos;
    }
    
    public void setUsuarioJuegos(Set usuarioJuegos) {
        this.usuarioJuegos = usuarioJuegos;
    }
    public Set getJuegoSorteos() {
        return this.juegoSorteos;
    }
    
    public void setJuegoSorteos(Set juegoSorteos) {
        this.juegoSorteos = juegoSorteos;
    }




}


