package entity;
// Generated Jun 14, 2017 10:42:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Medico generated by hbm2java
 */
public class Medico  implements java.io.Serializable {


     private int idMedico;
     private String nombreMedico;
     private String rutMedico;
     private String especialidadMedico;
     private Set detalleBonos = new HashSet(0);

    public Medico() {
    }

	
    public Medico(int idMedico, String nombreMedico, String rutMedico) {
        this.idMedico = idMedico;
        this.nombreMedico = nombreMedico;
        this.rutMedico = rutMedico;
    }
    public Medico(int idMedico, String nombreMedico, String rutMedico, String especialidadMedico, Set detalleBonos) {
       this.idMedico = idMedico;
       this.nombreMedico = nombreMedico;
       this.rutMedico = rutMedico;
       this.especialidadMedico = especialidadMedico;
       this.detalleBonos = detalleBonos;
    }
   
    public int getIdMedico() {
        return this.idMedico;
    }
    
    public void setIdMedico(int idMedico) {
        this.idMedico = idMedico;
    }
    public String getNombreMedico() {
        return this.nombreMedico;
    }
    
    public void setNombreMedico(String nombreMedico) {
        this.nombreMedico = nombreMedico;
    }
    public String getRutMedico() {
        return this.rutMedico;
    }
    
    public void setRutMedico(String rutMedico) {
        this.rutMedico = rutMedico;
    }
    public String getEspecialidadMedico() {
        return this.especialidadMedico;
    }
    
    public void setEspecialidadMedico(String especialidadMedico) {
        this.especialidadMedico = especialidadMedico;
    }
    public Set getDetalleBonos() {
        return this.detalleBonos;
    }
    
    public void setDetalleBonos(Set detalleBonos) {
        this.detalleBonos = detalleBonos;
    }




}


