package entity;
// Generated Jun 14, 2017 10:42:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Oficina generated by hbm2java
 */
public class Oficina  implements java.io.Serializable {


     private int idOficina;
     private String direccionOficina;
     private Set supervisors = new HashSet(0);
     private Set bonos = new HashSet(0);

    public Oficina() {
    }

	
    public Oficina(int idOficina, String direccionOficina) {
        this.idOficina = idOficina;
        this.direccionOficina = direccionOficina;
    }
    public Oficina(int idOficina, String direccionOficina, Set supervisors, Set bonos) {
       this.idOficina = idOficina;
       this.direccionOficina = direccionOficina;
       this.supervisors = supervisors;
       this.bonos = bonos;
    }
   
    public int getIdOficina() {
        return this.idOficina;
    }
    
    public void setIdOficina(int idOficina) {
        this.idOficina = idOficina;
    }
    public String getDireccionOficina() {
        return this.direccionOficina;
    }
    
    public void setDireccionOficina(String direccionOficina) {
        this.direccionOficina = direccionOficina;
    }
    public Set getSupervisors() {
        return this.supervisors;
    }
    
    public void setSupervisors(Set supervisors) {
        this.supervisors = supervisors;
    }
    public Set getBonos() {
        return this.bonos;
    }
    
    public void setBonos(Set bonos) {
        this.bonos = bonos;
    }




}


