package entity;
// Generated Jun 14, 2017 10:42:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Paciente generated by hbm2java
 */
public class Paciente  implements java.io.Serializable {


     private int idPaciente;
     private Cotizante cotizante;
     private String nombrePaciente;
     private String apellidoPaciente;
     private String rutPaciente;
     private Set bonos = new HashSet(0);

    public Paciente() {
    }

	
    public Paciente(int idPaciente, Cotizante cotizante, String nombrePaciente, String apellidoPaciente, String rutPaciente) {
        this.idPaciente = idPaciente;
        this.cotizante = cotizante;
        this.nombrePaciente = nombrePaciente;
        this.apellidoPaciente = apellidoPaciente;
        this.rutPaciente = rutPaciente;
    }
    public Paciente(int idPaciente, Cotizante cotizante, String nombrePaciente, String apellidoPaciente, String rutPaciente, Set bonos) {
       this.idPaciente = idPaciente;
       this.cotizante = cotizante;
       this.nombrePaciente = nombrePaciente;
       this.apellidoPaciente = apellidoPaciente;
       this.rutPaciente = rutPaciente;
       this.bonos = bonos;
    }
   
    public int getIdPaciente() {
        return this.idPaciente;
    }
    
    public void setIdPaciente(int idPaciente) {
        this.idPaciente = idPaciente;
    }
    public Cotizante getCotizante() {
        return this.cotizante;
    }
    
    public void setCotizante(Cotizante cotizante) {
        this.cotizante = cotizante;
    }
    public String getNombrePaciente() {
        return this.nombrePaciente;
    }
    
    public void setNombrePaciente(String nombrePaciente) {
        this.nombrePaciente = nombrePaciente;
    }
    public String getApellidoPaciente() {
        return this.apellidoPaciente;
    }
    
    public void setApellidoPaciente(String apellidoPaciente) {
        this.apellidoPaciente = apellidoPaciente;
    }
    public String getRutPaciente() {
        return this.rutPaciente;
    }
    
    public void setRutPaciente(String rutPaciente) {
        this.rutPaciente = rutPaciente;
    }
    public Set getBonos() {
        return this.bonos;
    }
    
    public void setBonos(Set bonos) {
        this.bonos = bonos;
    }




}


