package entity;
// Generated Jun 14, 2017 10:42:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Plan generated by hbm2java
 */
public class Plan  implements java.io.Serializable {


     private int idPlan;
     private String nombrePlan;
     private double factorConv;
     private Set previsions = new HashSet(0);

    public Plan() {
    }

	
    public Plan(int idPlan, String nombrePlan, double factorConv) {
        this.idPlan = idPlan;
        this.nombrePlan = nombrePlan;
        this.factorConv = factorConv;
    }
    public Plan(int idPlan, String nombrePlan, double factorConv, Set previsions) {
       this.idPlan = idPlan;
       this.nombrePlan = nombrePlan;
       this.factorConv = factorConv;
       this.previsions = previsions;
    }
   
    public int getIdPlan() {
        return this.idPlan;
    }
    
    public void setIdPlan(int idPlan) {
        this.idPlan = idPlan;
    }
    public String getNombrePlan() {
        return this.nombrePlan;
    }
    
    public void setNombrePlan(String nombrePlan) {
        this.nombrePlan = nombrePlan;
    }
    public double getFactorConv() {
        return this.factorConv;
    }
    
    public void setFactorConv(double factorConv) {
        this.factorConv = factorConv;
    }
    public Set getPrevisions() {
        return this.previsions;
    }
    
    public void setPrevisions(Set previsions) {
        this.previsions = previsions;
    }




}


