package entity;
// Generated Jun 22, 2017 9:58:54 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pozo generated by hbm2java
 */
public class Pozo  implements java.io.Serializable {


     private int idPozo;
     private int pozo;
     private Set usuarios = new HashSet(0);
     private Set sorteos = new HashSet(0);

    public Pozo() {
    }

	
    public Pozo(int idPozo, int pozo) {
        this.idPozo = idPozo;
        this.pozo = pozo;
    }
    public Pozo(int idPozo, int pozo, Set usuarios, Set sorteos) {
       this.idPozo = idPozo;
       this.pozo = pozo;
       this.usuarios = usuarios;
       this.sorteos = sorteos;
    }
   
    public int getIdPozo() {
        return this.idPozo;
    }
    
    public void setIdPozo(int idPozo) {
        this.idPozo = idPozo;
    }
    public int getPozo() {
        return this.pozo;
    }
    
    public void setPozo(int pozo) {
        this.pozo = pozo;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }
    public Set getSorteos() {
        return this.sorteos;
    }
    
    public void setSorteos(Set sorteos) {
        this.sorteos = sorteos;
    }




}


