package entity;
// Generated Jun 14, 2017 10:42:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Prevision generated by hbm2java
 */
public class Prevision  implements java.io.Serializable {


     private int idPrevision;
     private Plan plan;
     private String nombrePrevision;
     private Set cotizantes = new HashSet(0);

    public Prevision() {
    }

	
    public Prevision(int idPrevision) {
        this.idPrevision = idPrevision;
    }
    public Prevision(int idPrevision, Plan plan, String nombrePrevision, Set cotizantes) {
       this.idPrevision = idPrevision;
       this.plan = plan;
       this.nombrePrevision = nombrePrevision;
       this.cotizantes = cotizantes;
    }
   
    public int getIdPrevision() {
        return this.idPrevision;
    }
    
    public void setIdPrevision(int idPrevision) {
        this.idPrevision = idPrevision;
    }
    public Plan getPlan() {
        return this.plan;
    }
    
    public void setPlan(Plan plan) {
        this.plan = plan;
    }
    public String getNombrePrevision() {
        return this.nombrePrevision;
    }
    
    public void setNombrePrevision(String nombrePrevision) {
        this.nombrePrevision = nombrePrevision;
    }
    public Set getCotizantes() {
        return this.cotizantes;
    }
    
    public void setCotizantes(Set cotizantes) {
        this.cotizantes = cotizantes;
    }




}


