package entity;
// Generated Jun 14, 2017 10:42:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Seguro generated by hbm2java
 */
public class Seguro  implements java.io.Serializable {


     private int idSeguro;
     private String nombreSeguro;
     private String nombreCompaniaAseguradora;
     private Set cotizantes = new HashSet(0);

    public Seguro() {
    }

	
    public Seguro(int idSeguro) {
        this.idSeguro = idSeguro;
    }
    public Seguro(int idSeguro, String nombreSeguro, String nombreCompaniaAseguradora, Set cotizantes) {
       this.idSeguro = idSeguro;
       this.nombreSeguro = nombreSeguro;
       this.nombreCompaniaAseguradora = nombreCompaniaAseguradora;
       this.cotizantes = cotizantes;
    }
   
    public int getIdSeguro() {
        return this.idSeguro;
    }
    
    public void setIdSeguro(int idSeguro) {
        this.idSeguro = idSeguro;
    }
    public String getNombreSeguro() {
        return this.nombreSeguro;
    }
    
    public void setNombreSeguro(String nombreSeguro) {
        this.nombreSeguro = nombreSeguro;
    }
    public String getNombreCompaniaAseguradora() {
        return this.nombreCompaniaAseguradora;
    }
    
    public void setNombreCompaniaAseguradora(String nombreCompaniaAseguradora) {
        this.nombreCompaniaAseguradora = nombreCompaniaAseguradora;
    }
    public Set getCotizantes() {
        return this.cotizantes;
    }
    
    public void setCotizantes(Set cotizantes) {
        this.cotizantes = cotizantes;
    }




}


