package entity;
// Generated Jun 14, 2017 10:42:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sociedad generated by hbm2java
 */
public class Sociedad  implements java.io.Serializable {


     private String idSociedad;
     private String nombreSociedad;
     private String rutSociedad;
     private Set bonos = new HashSet(0);

    public Sociedad() {
    }

	
    public Sociedad(String idSociedad, String nombreSociedad, String rutSociedad) {
        this.idSociedad = idSociedad;
        this.nombreSociedad = nombreSociedad;
        this.rutSociedad = rutSociedad;
    }
    public Sociedad(String idSociedad, String nombreSociedad, String rutSociedad, Set bonos) {
       this.idSociedad = idSociedad;
       this.nombreSociedad = nombreSociedad;
       this.rutSociedad = rutSociedad;
       this.bonos = bonos;
    }
   
    public String getIdSociedad() {
        return this.idSociedad;
    }
    
    public void setIdSociedad(String idSociedad) {
        this.idSociedad = idSociedad;
    }
    public String getNombreSociedad() {
        return this.nombreSociedad;
    }
    
    public void setNombreSociedad(String nombreSociedad) {
        this.nombreSociedad = nombreSociedad;
    }
    public String getRutSociedad() {
        return this.rutSociedad;
    }
    
    public void setRutSociedad(String rutSociedad) {
        this.rutSociedad = rutSociedad;
    }
    public Set getBonos() {
        return this.bonos;
    }
    
    public void setBonos(Set bonos) {
        this.bonos = bonos;
    }




}


