package entity;
// Generated Jun 14, 2017 10:42:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Supervisor generated by hbm2java
 */
public class Supervisor  implements java.io.Serializable {


     private int idSupervisor;
     private Oficina oficina;
     private String nombreSupervisor;
     private Set cajeros = new HashSet(0);

    public Supervisor() {
    }

	
    public Supervisor(int idSupervisor, Oficina oficina, String nombreSupervisor) {
        this.idSupervisor = idSupervisor;
        this.oficina = oficina;
        this.nombreSupervisor = nombreSupervisor;
    }
    public Supervisor(int idSupervisor, Oficina oficina, String nombreSupervisor, Set cajeros) {
       this.idSupervisor = idSupervisor;
       this.oficina = oficina;
       this.nombreSupervisor = nombreSupervisor;
       this.cajeros = cajeros;
    }
   
    public int getIdSupervisor() {
        return this.idSupervisor;
    }
    
    public void setIdSupervisor(int idSupervisor) {
        this.idSupervisor = idSupervisor;
    }
    public Oficina getOficina() {
        return this.oficina;
    }
    
    public void setOficina(Oficina oficina) {
        this.oficina = oficina;
    }
    public String getNombreSupervisor() {
        return this.nombreSupervisor;
    }
    
    public void setNombreSupervisor(String nombreSupervisor) {
        this.nombreSupervisor = nombreSupervisor;
    }
    public Set getCajeros() {
        return this.cajeros;
    }
    
    public void setCajeros(Set cajeros) {
        this.cajeros = cajeros;
    }




}


