package entity;
// Generated Jun 22, 2017 9:58:54 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private Perfil perfil;
     private Pozo pozo;
     private String nombreUsuario;
     private String nombre;
     private String apellido;
     private String password;
     private int fondo;
     private int estado;
     private Set usuarioJuegos = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(int idUsuario, Perfil perfil, Pozo pozo, String nombreUsuario, String nombre, String apellido, String password, int fondo, int estado) {
        this.idUsuario = idUsuario;
        this.perfil = perfil;
        this.pozo = pozo;
        this.nombreUsuario = nombreUsuario;
        this.nombre = nombre;
        this.apellido = apellido;
        this.password = password;
        this.fondo = fondo;
        this.estado = estado;
    }
    public Usuario(int idUsuario, Perfil perfil, Pozo pozo, String nombreUsuario, String nombre, String apellido, String password, int fondo, int estado, Set usuarioJuegos) {
       this.idUsuario = idUsuario;
       this.perfil = perfil;
       this.pozo = pozo;
       this.nombreUsuario = nombreUsuario;
       this.nombre = nombre;
       this.apellido = apellido;
       this.password = password;
       this.fondo = fondo;
       this.estado = estado;
       this.usuarioJuegos = usuarioJuegos;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Perfil getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }
    public Pozo getPozo() {
        return this.pozo;
    }
    
    public void setPozo(Pozo pozo) {
        this.pozo = pozo;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public int getFondo() {
        return this.fondo;
    }
    
    public void setFondo(int fondo) {
        this.fondo = fondo;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }
    public Set getUsuarioJuegos() {
        return this.usuarioJuegos;
    }
    
    public void setUsuarioJuegos(Set usuarioJuegos) {
        this.usuarioJuegos = usuarioJuegos;
    }




}


