package entity;
// Generated Jun 22, 2017 9:58:54 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UsuarioJuego generated by hbm2java
 */
public class UsuarioJuego  implements java.io.Serializable {


     private int idUsuarioJuego;
     private Juego juego;
     private Usuario usuario;
     private int fechaJuego;
     private Set historialGanadoreses = new HashSet(0);

    public UsuarioJuego() {
    }

	
    public UsuarioJuego(int idUsuarioJuego, Juego juego, Usuario usuario, int fechaJuego) {
        this.idUsuarioJuego = idUsuarioJuego;
        this.juego = juego;
        this.usuario = usuario;
        this.fechaJuego = fechaJuego;
    }
    public UsuarioJuego(int idUsuarioJuego, Juego juego, Usuario usuario, int fechaJuego, Set historialGanadoreses) {
       this.idUsuarioJuego = idUsuarioJuego;
       this.juego = juego;
       this.usuario = usuario;
       this.fechaJuego = fechaJuego;
       this.historialGanadoreses = historialGanadoreses;
    }
   
    public int getIdUsuarioJuego() {
        return this.idUsuarioJuego;
    }
    
    public void setIdUsuarioJuego(int idUsuarioJuego) {
        this.idUsuarioJuego = idUsuarioJuego;
    }
    public Juego getJuego() {
        return this.juego;
    }
    
    public void setJuego(Juego juego) {
        this.juego = juego;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public int getFechaJuego() {
        return this.fechaJuego;
    }
    
    public void setFechaJuego(int fechaJuego) {
        this.fechaJuego = fechaJuego;
    }
    public Set getHistorialGanadoreses() {
        return this.historialGanadoreses;
    }
    
    public void setHistorialGanadoreses(Set historialGanadoreses) {
        this.historialGanadoreses = historialGanadoreses;
    }




}


